### ISSUE TITLE
Assertion failed: new_time >= loop->time

### ISSUE THREAD

**Issue by Jan-Kruse** [libuv/libuv#1633]
* **Version**: 1.16.1
* **Platform**: Windows 7 64 Bit

Using latest node.js (libuv version 1.16.1) on my machine, causes the following error:
`Assertion failed: new_time >= loop->time, file src\win\timer.c, line 37`

I'm using a **non overclocked** AMD FX-6300. Yesterday it worked fine, but after a reboot it does not work anymore.

**Comment by bnoordhuis** [comment]
It means the system clock is drifting.  It's not a libuv issue; libuv merely detects it and aborts.

You might be able to work around it by selecting a different clock source, e.g. ACPI instead of TSC (although I have no idea how you do that on Windows), or by tweaking settings in the BIOS.

**Comment by Jan-Kruse** [comment]
The issue was fixed by doing a CMOS reset on my system.

**Comment by refack** [comment]
@Jan-Kruse You might also want to check your onboard CMOS backup battery 
![image](https://user-images.githubusercontent.com/96947/33085286-4a91c472-ceb2-11e7-9cfc-3c15a35dc1c4.png)

**Comment by natewatson999** [comment]
I encountered this issue in an Amazon AWS EC2 Windows Server instance. I'm not sure if I can do a CMOS reset in that context.

**Comment by bnoordhuis** [comment]
@natewatson999 If nothing/no one touched the system clock then you should probably file an issue with AWS because that sounds like a bug.

**Comment by agarcian** [comment]
I am experiencing the same issue in an AWS EC2 Windows server. This is a long running job and it fails in Windows only.

**Comment by Jan-Kruse** [comment]
In my case my investigations showed, that using the X-Boost Feature of my ASRock main board caused this error in Windows. Maybe Amazon ist using a similiar feature in their server hardware. Which windows version are you on?

Am 10.02.2018 um 22:19 schrieb Andres Garcia <notifications@github.com<mailto:notifications@github.com>>:


I am experiencing the same issue in an AWS EC2 Windows server. This is a long running job and it fails in Windows only.

**Comment by jdmayfield** [comment]
I am getting this on both node.js and nw.js on a Win7 VM inside virtualbox.  I haven't seen it happen on the host, which is running on Linux Mint.

Is there a way to prevent this in my code?  I'm trying to run a node-based Windows Service and this periodically crashes it.

**Comment by amoltivarekar** [comment]
> * **Version**: 1.16.1
> * **Platform**: Windows 7 64 Bit
> 
> Using latest node.js (libuv version 1.16.1) on my machine, causes the following error:
> `Assertion failed: new_time >= loop->time, file src\win\timer.c, line 37`
> 
> I'm using a **non overclocked** AMD FX-6300. Yesterday it worked fine, but after a reboot it does not work anymore.

Hi, I'm facing same issue using react-native with expo , how can i fix it.. please help me.

**Comment by izk1989** [comment]
I am having the same issue, and i have the exact same cpu, non overclocked. Any solutions?
Assertion failed: new_time >= loop->time, file src\win\core.c, line 309t@1.2.0

**Comment by JLarky** [comment]
> I am experiencing the same issue in an AWS EC2 Windows server. This is a long running job and it fails in Windows only.

so far for me the only solution was to restart ec2 instance

**Comment by pgrm** [comment]
I have this error on a newly set up xps 13 2 in 1 with ice lake chip with windows 10. I tried restarting multiple times, but it didn't help. The clock is off by 1 second compared to https://www.timeanddate.com/ and it should be the correct UTC time. What's even weirder, when I run the tool in WSL on the very same machine, it works and doesn't complain.

WSL is a good workaround, but it would be nice if it were also working directly in windows. Any ideas?

**Comment by Yonom** [comment]
@pgrm I too have the same problem. Did you manage to fix the issue in Windows?

My setup:
XPS 13 2 in 1 7390
i7-1065G7
Windows 10 Home 1903 Build 18362.356
Node 10.16.3 LTS

**Comment by pgrm** [comment]
@Yonom no I did not, I'm simply using WSL for everything. I actually used the latest node 12 installed via chocolatey.

funny that you have the same processor, might it be something hardware related that is now done differently?

**Comment by Yonom** [comment]
I've messed around with a few BIOS settings (under Performance tab) but could not fix the issue. I'm running the OEM version of Windows, maybe that's the one causing problems. 
I won't have time to reinstall windows so I'll just stick to the WSL workaround for now.

**Comment by suavelizard** [comment]
All of these brand new Icelake systems have incorrect system clocks?

**Comment by bnoordhuis** [comment]
Maybe on Ice Lake the return value of `QueryPerformanceCounter()` isn't stable, e.g., when the process gets migrated to a different core? I have no way to test myself but if someone wants to investigate and post the results, we'll see what we can do.

I haven't tested it myself but someone suggested that switching the clock source from TSC to HPET with `bcdedit /set useplatformclock true` fixed the issue.

**Comment by etjh** [comment]
I had same problem on my new XPS.
Upgrading to new Dell drivers solved my problem for login to heroku.

**Comment by paul-at** [comment]
Having same issue on Surface Pro 7 with latest driver and firmware updates. This issue definitely should be reopened.

**Comment by Pala2812** [comment]
can also reproduce it with Surface Pro 7 i7-1065G7 when working with firebase

**Comment by suavelizard** [comment]
This was indeed an Icelake issue and not libuv. New firmware update should resolve.

**Comment by paul-at** [comment]
@suavelizard could you share a link to this update? I have the latest Surface Pro 7 firmware installed, and still experience this issue. There are no updates in Intel website either (https://downloadcenter.intel.com/product/196597/intel-core-i7-1065g7-processor-8m-cache-up-to-3-90-ghz)

**Comment by doru15** [comment]
I have a Lenovo Yoga C940 with same i7-1065G7 and i got same error. Is there a fix available?

**Comment by zilched0** [comment]
anyone resolved this?

**Comment by jansen-teh** [comment]
So far, I've tried:
- `bcdedit /set useplatformclock true` 
- Latest update of Windows Insider Program, Fast Ring
- Latest firmware from Lenovo

The problem still exists.
I use Lenovo C940 with i7-1065G7.

Has anyone resolved this already?

**Comment by saschanaz** [comment]
Also Surface Pro 7 i7-1065G7 here. Could this be something with Intel 10xx series CPU?

**Comment by kmdavid3** [comment]
We faced the same issue using nodejs and firebase-tools.
we tried to update the bios but the problem was still there and when switched from node version 12.6.1 the problem was resolved.

**Comment by rejhgadellaa** [comment]
@kmdavid3 which version of node did you switch to? I'm running 12.6.1.

**Comment by kmdavid3** [comment]
from node 10.16.3 to node 12.6.1

**Comment by saschanaz** [comment]
@rejhgadellaa Out of curiosity, are you also using Windows and Intel 10xx CPU?

**Comment by rejhgadellaa** [comment]
Yes, Surface Laptop 3, i7-1065G7 and Windows 10. Still getting the issue.

Tried latest firmware, upgrading node to 12.6.3, no luck so far.

**Comment by zilched0** [comment]
Quick update, on my Surface Pro 7, I moved over to WSL v1 about a month ago and haven't seen the issue since (fingers crossed)... Might be an option?

**Comment by rejhgadellaa** [comment]
@zilched0 WSL fixes it for me. Super. Weird. So.. it's powershell/windows' own subsystem that gets it wrong?

**Comment by Parakoos** [comment]
Can someone explain what you mean by 'switch to WSL'? I'm trying to run firebase emulator and it keeps erroring with the weird Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 309

**Comment by kmdavid3** [comment]
[check this out](https://www.laurentbloch.net/MySpip3/Installer-les-services-Linux-de-Windows-10-WSL)

**Comment by zilched0** [comment]
Using the Windows Subsystem for Linux (WSL) allows you to run Ubuntu (or another distribution) from within Windows. Another link: https://www.smashingmagazine.com/2019/09/moving-javascript-development-bash-windows/

**Comment by NNskelly** [comment]
Just adding my voice to the noise to reaffirm the scope of the problem: same issue on an HP Spectre x360 13-aw0xxx purchased late last year, Node 12.14.0 Win10 version 1903.  Installing a whole Linux distro to run a single node script sounds like overkill, or at least more of a hassle than temporarily turning off some functionality in my codebase so I don't even invoke timing sensitivity, so hoping this gets properly fixed soon on SOMEONE'S end!

**Comment by saschanaz** [comment]
Could someone call a person from Microsoft or Intel to investigate this? 🤔

**Comment by anarmammad** [comment]
Experiencing same problem:
- Dell Inspiron 15 5593
- Windows 10 Home v1909
- node v12.16.1 
It's a pity that WSL is not an option :(

**Comment by joshxyzhimself** [comment]
On my case it was me switching up settings in my AMD Overdrive

![image](https://user-images.githubusercontent.com/60829711/79066915-ec31c700-7ced-11ea-86c8-906ca7251a04.png)

I had moved the sliders to 38x and time drift error popped up.

Had to move it back to the previous 39x.

**Comment by danielcomes** [comment]
Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 309

In hp

Intel core i5-1035G7
win 10 home

**Comment by soraryu** [comment]
Same issue here. Also on 10th gen Intel processor. In my case it's a i7-1035G7.

**Comment by danielcomes** [comment]
> Same issue here. Also on 10th gen Intel processor. In my case it's a i7-1035G7.

Hey!, I solved it installing WSL, try with that

**Comment by swve** [comment]
Same issue here, with Intel Core i5-10XXX

**Comment by NNskelly** [comment]
An aside for anyone setting up WSL to remedy this for a NodeJS project that happens to include libuv pre/compiled dependencies (e.g. Firebase RTDB's websockets): yes, WSL solves the timing bug, but it may not be a smooth ride on all other fronts.  Specifically, I've needed to do things like 

- re-mount the project drive with metadata enabled per https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/ to help alleviate npm installs erroring out on file staging/copy/delete operations (and then sometimes just repeat installs until they go through- there may still be some timing races between when WSL makes files and when they're fully available to read back)
-- `sudo umount /mnt/c` (or desired drive letter)
-- `sudo mount -t drvfs C: /mnt/c -o metadata` (or desired drive letter; may also include manual owner/access reassignment to something less restrictive than root, e.g. `-o metadata,uid=1000,gid=1000,umask=22,fmask=111` )
- manually run installs with expanded --stack-size to resolve max-stack-exceeded errors which seem far more prevalent on WSL than native:
-- use `ulimit -a` to see what stack size your setup caps out at; expect 8192(kb) or so
-- use `node --stack-size=XXXX` with a value not exceeding the ulimit stack size (2000 or so seems good) to tell node, for the duration of 1 run, that it can use more stack
-- for npm installs, manually invoke npm via `node --stack-size=XXXX /path/to/your/local/lib/node_modules/npm/bin/npm-cli.js install ...`
--- expect the path to be at or around /home/USERNAME/.nvm/versions/node/vER.SI.ON/lib/node_modules/npm/bin/npm-cli.js
- uninstall any modules that you previously installed globally in pure-windows, and which may have set env/path info to their Windows installations which WSL may pick up on and try to run anyway (I'm looking at you, Firebase), then relaunch the WSL shell and global-install them there

**Comment by benyaminahmed** [comment]
I hit this problem with '**firebase deploy**'

This is my stem spec:

![image](https://user-images.githubusercontent.com/36366023/80307878-d4654300-87c3-11ea-8033-f87773b9d332.png)

`Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 309`

Without a fix for this I am stuck! Don't fancy installing WSL!

**Comment by Parakoos** [comment]
> I hit this problem with '**firebase deploy**'
> `Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 309`

I get this with firebase as well! But, it usually works if I do it twice in a row. But, running the firebase emulator doesn't work. Same error. And that one I can't run again. Right now, I'm simply not using the emulator. I tried WSL, and it works, but it is such a hassle to have to npm install everything from a unix perspective. 

I can't believe that this is such a common error with i7-1065G7 CPUs and no one is fixing it! This is a big deal!

**Comment by addaleax** [comment]
> I can't believe that this is such a common error with i7-1065G7 CPUs and no one is fixing it! This is a big deal!

To be clear, all signs point to this being a bug in Windows, not in libuv.

I’ve opened https://github.com/libuv/libuv/pull/2814 that should at least keep libuv from outright crashing, if it is accepted.

**Comment by soraryu** [comment]
@addaleax thank you. Are you by chance aware of any workaround? I'm here as a user where software (in this case Unity 3D game engine) that deep inside uses node.js and libuv is crashing on that specific Intel processor, and I can't do anything about it right now.

**Comment by addaleax** [comment]
@soraryu Only the one already mentioned in this thread:

> I haven't tested it myself but someone suggested that switching the clock source from TSC to HPET with `bcdedit /set useplatformclock true` fixed the issue.

**Comment by soraryu** [comment]
OK, tested, and can not confirm - that command does not fix the assertion in libuv in node.js.

**Comment by jansen-teh** [comment]
Hmmm weird..
I accidentally did something and it suddenly worked.

I turned off the BitLocker Drive Encryption for my C:. This is where I installed my NodeJS.
(Up to this point, I don't know if the error still occurred.)
I turned on the encryption again, and then turned off and on hibernation via
```
powercfg -h off/on
```

I don't know if this will work for everybody, but hopefully, it will. ✌
As for the reason why it works, I don't know why.
I can just assume that decrypting and re-encrypting the drive fixes something.
Pretty sure that hibernation thing didn't have anything to do with this issue though.

**Comment by bzoz** [comment]
@pgrm @Yonom @Sicofonia @paul-at @Pala2812 @doru15 @zilched0 @jansen-teh @saschanaz @kmdavid3 @Parakoos @NNskelly @anarmammad @danielcomes @soraryu @swve @benyaminahmed 
Could you run the program attached in the zip: [qpc-test.zip](https://github.com/libuv/libuv/files/4594707/qpc-test.zip)
If you prefer the source code is here: https://gist.github.com/bzoz/b9f942425007a0f834cae2dcc253f1df, I can prepare the instructions on how to get a compiler and built it yourselves if you want.

The program will either do nothing or produce an output like this:
![image](https://user-images.githubusercontent.com/17704638/81326661-71fd2400-909a-11ea-97d9-1a8e2c745003.png)
if it does so, sharing those numbers would be a great help.

**Comment by saschanaz** [comment]
@bzoz Built it myself with clang 9.0.1 and it prints nothing.

**Comment by Pala2812** [comment]
i did run the program, but it didn't ouput any numbers even when scrolled to the end of the console.

If it helps i can post my system configurations.

**Comment by soraryu** [comment]
Same here. It saturates one CPU core but does not print anything. I assume this just checks if time deltas are actually negative?

**Comment by soraryu** [comment]
@bnoordhuis can you or someone else please reopen this issue. It is still ongoing and preventing entire categories of devices from working correctly.

**Comment by bnoordhuis** [comment]
Again, it's _not_ a libuv issue. We've done some investigations and we might add a workaround (but then again, we might not) but the tree that you really should be barking up is Microsoft's or Intel's. That goes for everyone in this thread.

**Comment by soraryu** [comment]
Have you reported the issue to them? If you feel this is an upstream issue with someone else you should not just try to push that back. All the people having issues with this see the crash happening in libuv, as demonstrated adding a (even temporary) workaround would be possible, yet you seem adamant that this has nothing to do with libuv at all.
What's your suggestion until Microsoft or Intel do or not do fix the assumed underlying issue? That people hack around libuv?

**Comment by saschanaz** [comment]
@bnoordhuis Do you have a Microsoft contact for investigation here?

**Comment by bnoordhuis** [comment]
@soraryu I haven't, because I don't have an affected system. You have, so you should.

@saschanaz Unfortunately, no. I don't know anyone at Intel you could reach out directly to either.

I'd log a support issue through the regular channels. Someone at MS or Intel will take notice when enough people do.

**Comment by saschanaz** [comment]
I've reported an issue on Windows Feedback: https://aka.ms/AA7ujea

**Comment by soraryu** [comment]
Thanks @saschanaz . 
@bnoordhuis I'm just a regular Unity user, I wouldn't even have known that libuv existed nor what a QPC is.  I'm just trying to unblock my team here.

Is the Feedback Hub the "regular channel" for submitting issues to Microsoft? What's the "regular channel" for Intel?

**Comment by saschanaz** [comment]
> Did you get any feedback?

Not so far. Please do "Add similar feedback" for them to notice.

>Is the Feedback Hub the "regular channel" for submitting issues to Microsoft?

Right.

**Comment by bzoz** [comment]
@saschanaz could you try this: https://gist.github.com/bzoz/52b1d45ce6a27418f31d58956e72e4c0 - it behaves a little more like libuv, it will create threads that write and read files. The output should look like this:
```
Initial: 1182799683516, freq: 10000000
still running..
still running..
```
etc.

Could you compile and run it and share the output? It will help in our investigation.

**Comment by saschanaz** [comment]
@bzoz It runs silently:

```
Initial: 272692642196, freq: 10000000
still running..
still running..
still running..
still running..
```

**Comment by bzoz** [comment]
@saschanaz does this issue happen on other Node apps? Can you try maybe running VSCode?

**Comment by saschanaz** [comment]
VSCode never crashes as I have used it for several months.

**Comment by 9numbernine9** [comment]
I'm running into the same issue as others in this thread, and like some others I'm using a new Dell XPS 13 2-in-1 9300 with the i7-1065G7 CPU. 

After a quick reboot into the BIOS, it appears that my machine is running BIOS version `1.0.6`. A newer version, `1.0.7`, was released on 2020-04-06. Unfortunately for me, my laptop is a work laptop and I don't have privileges to apply BIOS updates, so I can't test if this version will fix the problem or not (and due to _current global events_ I'm not exactly in the office much these days). The release notes mention "microcode updates" which is not really specific enough to know if this can fix the issue or not.

Is there anyone else on this thread that has a Dell XPS 13 9300 with this CPU _and that is comfortable installing BIOS updates_ that would be willing to try this update on the behalf of the rest of us?

**Comment by bzoz** [comment]
@saschanaz are you willing to run your repo with instrumented Node? I can provide the binary or the instructions on how to build one and a patch that will add some more logging.

**Comment by saschanaz** [comment]
@bzoz Sure. I prefer building one myself as this is a work machine.

**Comment by bzoz** [comment]
@saschanaz the code is here: https://github.com/bzoz/node/tree/instrument-libuv-13-11-0

It will store the raw value returned by QueryPerfomacneCounter and show it when libuv detects the error: https://github.com/bzoz/node/commit/c06043ff11f50b0624a7ad1b8f2dbc96ecbb9e42.  Maybe we will be able to see what exact values are causing this. 

To build this you need MS Build Tools, NASM and Python. Run:
```
vcbuild package
```
This will put Node and npm in the `out\Release\node-v13.11.0-win-x64` folder. Dont worry about it complaining about not being able to find 7zip. Just add it to the path and run your repro steps. The output we should see will look like this:
```
Time error :
        new_time:       157124108
        new_raw:        1571241087588
        loop->time:     157124068
        loop->raw_time: 1571240688624
        GetLastError:   0
Assertion failed: new_time >= loop->time, file src\win\core.c, line 309
```

**Comment by saschanaz** [comment]
Well now this is interesting. The error does not happen with the local build while it still happens on Node.js v14.3.0. It seems your branch is a bit outdated, should it be updated?

**Comment by saschanaz** [comment]
I tried again with raw `v14.3.0` branch without your fix: The bug happens.
I cherry-picked your change on top of the branch: The bug does not happen.

But it's not supposed to be a fix, right? 🤔

**Comment by bzoz** [comment]
No, but I guess it changes the timing enough to make the bug not appear. Or its a compiler bug.

Could you maybe remove the `raw_time` from my patch, to make it as similar to stock libuv as possible and try again?

**Comment by saschanaz** [comment]
Tried it, did nothing. Commenting out the fprintf block does make the bug again, but it's no helpful then 🤔

**Comment by bzoz** [comment]
Could you maybe remove the `GetLastError()` and `assert()`, and flip the condition like this:
```c
void uv_update_time(uv_loop_t* loop) {
  int64_t new_raw;
  uint64_t new_time = uv__hrtime_ex(1000, &new_raw);
  if (!(new_time >= loop->time)) {
    fprintf(stderr, "Time error:\n"
                    "\tnew_time:       %lld\n"
                    "\tnew_raw:        %lld\n"
                    "\tloop->time:     %lld\n"
                    "\tloop->raw_time: %lld\n",
            new_time, new_raw, loop->time, loop->raw_time);
    fflush(stderr);
  }
  loop->time = new_time;
  loop->raw_time = new_raw;
}
```
(I'm guessing now, maybe its a compiler bug?)

Or maybe you can use the Node master, attach a debugger, and set a conditional breakpoint?

**Comment by saschanaz** [comment]
Your new code generates some logs:

```
> npm run fetch-idl

> tsjs-lib-generator@ fetch-idl C:\Users\Kagami\Documents\GitHub\TSJS-lib-generator
> tsc -p ./tsconfig.json && node ./lib/idlfetcher.js

Time error:
        new_time:       0
        new_raw:        112770380864
        loop->time:     11277029
        loop->raw_time: 112770291393
Time error:
        new_time:       0
        new_raw:        112770475486
        loop->time:     11277040
        loop->raw_time: 112770401247
Time error:
        new_time:       0
        new_raw:        112770486429
        loop->time:     11277047
        loop->raw_time: 112770478237
Time error:
        new_time:       0
        new_raw:        112770531914
        loop->time:     11277049
        loop->raw_time: 112770490045
Time error:
        new_time:       0
        new_raw:        112770551484
        loop->time:     11277054
        loop->raw_time: 112770541634
Time error:
        new_time:       0
        new_raw:        112770677732
        loop->time:     11277055
        loop->raw_time: 112770555091
Time error:
        new_time:       0
        new_raw:        112770744722
        loop->time:     11277068
        loop->raw_time: 112770685349
Time error:
        new_time:       0
        new_raw:        112770752099
        loop->time:     11277074
        loop->raw_time: 112770749475
Time error:
        new_time:       0
        new_raw:        112770905811
        loop->time:     11277075
        loop->raw_time: 112770755860
```

I'm not sure why `new_time` is 0 here 🤔

**Comment by bzoz** [comment]
If [QueryPerformanceCounter returned 0](https://github.com/libuv/libuv/blob/0356c65f04029d96870dff1f46483f9f8941f038/src/win/util.c#L501), the `new_time` would be uninitialized. Reading its value in the printf would be UB. Can you try this:

```c
void uv_update_time(uv_loop_t* loop) {
  int64_t new_raw = 0;
  uint64_t new_time = uv__hrtime_ex(1000, &new_raw);
  if (new_time < loop->time) {
    fprintf(stderr, "Time error:\n"
                    "\tnew_time:       %lld\n"
                    "\tnew_raw:        %lld\n"
                    "\tloop->time:     %lld\n"
                    "\tloop->raw_time: %lld\n",
            new_time, new_raw, loop->time, loop->raw_time);
    fflush(stderr);
  }
  loop->time = new_time;
  loop->raw_time = new_raw;
}
```

**Comment by saschanaz** [comment]
Tried it, setting `new_raw` as 0 removes the logs.

**Comment by bzoz** [comment]
I hope we are getting close: https://github.com/bzoz/node/commit/50901dd2221ff92206fbce7f922c6a99b32829dc

It basically takes the current libuv and changes the `assert` to an if-statement. It will print the old and the new time value. It might not reproduce, or we might get confirmation that uv__hrtime sometimes returns 0.

**Comment by saschanaz** [comment]
I get: `Error: uv__hrtime went from 6376013 to 0`

**Comment by saschanaz** [comment]
Weird, its documentation says [it should never return zero on modern Windows](https://docs.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancecounter) 🤔

**Comment by bzoz** [comment]
Yep, it should not.

Can you test one more: https://github.com/bzoz/node/commit/c57894331d1157b1065f22f18d84c745c7070f9e - it will GetLastError() if the QPC fails.

**Comment by saschanaz** [comment]
Same: `Error: uv__hrtime went from 7237920 to 0`

It's not QPC then.

**Comment by bzoz** [comment]
How about this: https://github.com/bzoz/node/commit/e97f150f94574d364740331dc5e3ba9a1ee49996

Just two more asserts. For whatever reason, we end up with 0 on this line: https://github.com/bzoz/node/blob/e97f150f94574d364740331dc5e3ba9a1ee49996/deps/uv/src/win/util.c#L507.

**Comment by saschanaz** [comment]
Well now this is embarrassing: `Assertion failed: scale != 0, file C:\Users\Kagami\Documents\GitHub\node\deps\uv\src\win\util.c, line 473`

**Comment by bzoz** [comment]
Can you try moving the `assert(scale != 0);` before the call to QPC? IDK, this looks like a compiler bug. We only call `hr__time` from `uv_update_time` with 1000 as scale and from `uv_hrtime` with 1000000000 as scale.

**Comment by saschanaz** [comment]
Will try, but it can't be solely a compiler bug since it only happens on certain CPUs. It should also happen on others if it was compiler.

**Comment by saschanaz** [comment]
Okay, tried it and it says same: `Assertion failed: scale != 0, file C:\Users\Kagami\Documents\GitHub\node\deps\uv\src\win\util.c, line 469`

Debugger says it's optimized out 👀

**Comment by bzoz** [comment]
Hm.. I'll try to rearrange some bits, I'll let you know when it is done.

BTW, thanks a lot!

**Comment by bzoz** [comment]
@saschanaz could you give this a spin: https://github.com/bzoz/node/commit/222b1e4d46ccb0d715272d3073cce91bb211fd24

It moves those math ops around, maybe it will help.

**Comment by saschanaz** [comment]
`Assertion failed: scale != 0, file C:\Users\Kagami\Documents\GitHub\node\deps\uv\src\win\util.c, line 469`

Debugger says it's from `uv_update_time` where it should always be 1000. Definitely something between MSVC and Intel CPUs.

**Comment by bzoz** [comment]
Definitely there is something off with the compiler, I'll get that reported to VS people.

In the meantime: maybe using `unsigned` instead of `double` for `scale` will help. Can you test this: https://github.com/bzoz/node/commit/7d904b50d26e3de831a50b6f11544e39647e24f5

**Comment by saschanaz** [comment]
Was trying same but with signed `int32_t` and it works 😄

**Comment by bzoz** [comment]
Yay! 

Can you test this one: https://github.com/bzoz/node/commit/710e1f6b6db681a1771cad1999b5fba53174c90b, its all those commits squashed and rebased onto current Node master. If that works, I'll open a PR.

**Comment by saschanaz** [comment]
It works 👍

**Comment by soraryu** [comment]
Thanks @bzoz and @saschanaz for following through with this and iterating on this so fast!

**Comment by saschanaz** [comment]
>I'll get that reported to VS people.

Is there a public channel or you'll contact them in private?

**Comment by bzoz** [comment]
@saschanaz I'll do that in the public issue tracker: https://developercommunity.visualstudio.com/spaces/8/index.html

Could you test if this branch reproduces: https://github.com/bzoz/node/tree/vsbug-repro? It is current v14.x Node with added `assert(scale != 0);`. Just to make sure we did not mess something up in the meantime. Also, can you check if you are running the latest VS2019?

**Comment by saschanaz** [comment]
@bzoz The branch does reproduce, with the latest VS2019 16.6.0.

**Comment by a2kapps** [comment]
i use firebase tools and i got this error : 
Assertion failed: new_time >= loop->time 

anyone can help me

**Comment by SureshKrishnaaR** [comment]
Try out this



> i use firebase tools and i got this error :
> Assertion failed: new_time >= loop->time
> 
> anyone can help me

Try out this......!
While installing firebase-tools use the following command:
                     npm install firebase-tools
Try not specifying -g.....!
It worked for me.
And also during login use this command:
                     firebase login: ci

**Comment by mendeljacks** [comment]
Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 309
Happens to me when making an axios request to a .jpg endpoint. 
The interesting thing is when I omit the s in https, it actually works, but with the s it breaks.

**Comment by ashok3612** [comment]
I get the following error while I run a "**firebase login**" command.
Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 309

And I have updated the latest firebase  [@admin.](https://github.com/libuv/libuv/commit/796744869669842bd5405a71de8ba60b1556fc24) 
But Still, I get the error.
How to fix it?

**PC Config:** hp fr1002tu
OS: win 10
processor: Intel i5 10th gen

**Comment by saschanaz** [comment]
For commenters: Currently the best thing to do is probably to wait for 15.0 where it's fixed.

**Comment by grao-github** [comment]
**Solved:**
I had the same issue with firebase on Windows 10. I simply **synchronized the clock**. There is a button called "Synchronize Your Clock"  under Date & Time settings.

**Comment by Lesiuk** [comment]
> For commenters: Currently the best thing to do is probably to wait for 15.0 where it's fixed.

But node 15.0 is going to be released in october. How are we supposed to write develop nodejs applications since then?

**Comment by saschanaz** [comment]
Maybe it should land also to 14 maybe? @bzoz

**Comment by grao-github** [comment]
> > For commenters: Currently the best thing to do is probably to wait for 15.0 where it's fixed.
> 
> But node 15.0 is going to be released in october. How are we supposed to develop nodejs applications until then?

did you try my suggestion above (synchronizing the clock)?

**Comment by Lesiuk** [comment]
> > > For commenters: Currently the best thing to do is probably to wait for 15.0 where it's fixed.
> > 
> > 
> > But node 15.0 is going to be released in october. How are we supposed to develop nodejs applications until then?
> 
> did you try my suggestion above (synchronizing the clock)?

Did not helped. I tried few times. I am using new Ice Lake Core i7-1065G7

**Comment by saschanaz** [comment]
It's known that this is because of possible compiler (or CPU) problem, so it's highly possible that there is no good workaround.

**Comment by Lesiuk** [comment]
Just compiled master branch with https://github.com/libuv/libuv/commit/796744869669842bd5405a71de8ba60b1556fc24 and everything works fine.

**Comment by ashok3612** [comment]
> Just compiled master branch with [7967448](https://github.com/libuv/libuv/commit/796744869669842bd5405a71de8ba60b1556fc24) and everything works fine. So I can confirm the fix works.

Could you explain me, how to do this?
Because i tried all the above steps. Nothing help me.

**Comment by Lesiuk** [comment]
> Could you explain me, how to do this?
> Because i tried all the above steps. Nothing help me.

Followed those steps https://github.com/nodejs/node/blob/master/BUILDING.md#windows to build nodejs from source with those changes.

**Comment by mendeljacks** [comment]
Syncing clock does nothing. This issue is affecting firebase-tools, heroku-cli, axios and other popular packages. It happens on dell xps 13 2 in 1 and other intel core i7 10th gen machines. The issue can be fixed by switching to node 8.11.1 (12 and 14 won't work). Alternatively it seems running node js from a docker container also works

**Comment by ashok3612** [comment]
1. Go to **services** and select **Automatic Time Zone Updater** and change **startup type** to **automatic**. Then click Apply and close.
2. Go to **date and time settings** and **sync your clock**.
3. Close existing cmd and open a new one and try with your command...
It fixed my assertion error problem. Finally, I can use firebase on node 14 also.
Try these two steps. It may fix your problem...

Cheeeerrrsss...

**Comment by Lesiuk** [comment]
It is not working on Intel ice lake CPUs.

**Comment by bzoz** [comment]
Newest Node release, [Node v14.6.0](https://nodejs.org/dist/v14.6.0/node-v14.6.0-x64.msi) contains the fix for this. Give it a spin.

**Comment by trinhpham** [comment]
Look like the fix work.
Do we have any plan to cherry-pick the fix to LTS versions of NodeJS?

**Comment by gengzhaoyun** [comment]
> It is not working on Intel ice lake CPUs.

Can you use nodejs in you PC now,  I also get the same error.
I use intel i7 1065G7 cpu

**Comment by trinhpham** [comment]
Hi @gengzhaoyun ,

AFAIK, all LTS versions have this fix already.
How is your node version `node -v` ?

**Comment by Milleruriol** [comment]
I upgraded NODEJS to the version [12.22.10](https://nodejs.org/download/release/v12.22.10/node-v12.22.10-x64.msi) and I don't see this issue anymore.

**Comment by yashvijaju** [comment]
Upgrading Node version to 16 fixed the error for me as well.

**Comment by Geolage** [comment]
> Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 309 Happens to me when making an axios request to a .jpg endpoint. The interesting thing is when I omit the s in https, it actually works, but with the s it breaks.

Bravo, dude! Ur answer exactly struck me, thx so much! Just simply change the protocol of request url by ignoring 's', then this annoying problem got resolved, though I still can't figure it out why...

**Comment by saschanaz** [comment]
> though I still can't figure it out why...

Uh... because you are still using old version of Node.js? 😬

**Comment by junbujianwpl** [comment]
> Maybe on Ice Lake the return value of `QueryPerformanceCounter()` isn't stable, e.g., when the process gets migrated to a different core? I have no way to test myself but if someone wants to investigate and post the results, we'll see what we can do.
> 
> I haven't tested it myself but someone suggested that switching the clock source from TSC to HPET with `bcdedit /set useplatformclock true` fixed the issue.

This one works for me. I ran a node project in a VirtualBox virtual machine.

**Comment by davidmrdavid** [comment]
Hey folks, I'm from the MSVC libraries team (ASan, MS STL, etc.). Our pipelines recently started getting hit by this assertion, and so I naturally stumbled upon this thread.

To my surprise, _it appears to me_ that the discussion here eventually converged to there possibly being an MSVC bug. Thankfully, that's my team!

I see mentions of a "compiler bug" in several comments:
- https://github.com/libuv/libuv/issues/1633#issuecomment-632375934
- https://github.com/libuv/libuv/issues/1633#issuecomment-633546947
- https://github.com/libuv/libuv/issues/1633#issuecomment-633552731
- and this PR which is equally informative: https://github.com/libuv/libuv/pull/2866

Though it appears this bug was reported via the Windows feedback form, not through "Developer Community" (https://developercommunity.visualstudio.com/cpp) which is our primary feedback forum.

So I had a few questions:
1. Did we conclude pretty decisively that this _looked_ like an msvc on intel chips error, and not an issue with the performance counter windows API?
2. Do we have any instructions on producing a repro? I'll try my luck at following the forks and links scattered throughout the thread here, though it's unclear to me if a standalone minimal repro was ever produced.

I am not a compiler developer (I do libs!) but with a minimal repro, I should be able to route this to our codegen folks to see if they can make sense of it. _Thanks!_

I'll ping a few folks who participated in those "compiler bug" investigations in case they can assist, though I understand that investigation is now 6 years old: @bzoz, @saschanaz

_Thanks!_

**Comment by davidmrdavid** [comment]
Related to the above: one of the MSVC codegen engineers analyzed the codegen produced by the toolset in the `libuv` source, and did not find any oddities

**Comment by saschanaz** [comment]
People reported this is fixed, are you saying it's reintroduced now? In latest node versions?

**Comment by davidmrdavid** [comment]
@saschanaz - Yes, but it's **different** from the bug y'all fixed. This difference wasn't clear to me when I first posted my comment here: https://github.com/libuv/libuv/issues/1633#issuecomment-4483070410 .

**For context:** MSVC and a handful of other teams at Microsoft are seeing this assertion fire intermittently in our engineering systems / pipelines that invoke Node (thus libuv) programs. We are using Node 20.

My understanding is that the issue that y'all resolved was some kind of MSVC code-gen issue, as the expanded commit message of https://github.com/libuv/libuv/commit/796744869669842bd5405a71de8ba60b1556fc24 describes. I think that fix is working as intended, as I confirmed here: https://github.com/libuv/libuv/issues/1633#issuecomment-4653429212 .

However, the assertion still fires. What we observe is that, sometimes, when a Node thread is moved between processors in a guest VM, hyper-v can fail to synchronize the TSCs (timestamp counters) of each processor. Therefore, in the new processor, `QueryPerformanceCounter` may return an earlier value so that `new_time >= loop->time` is `false`.

I explain in my PR (https://github.com/libuv/libuv/pull/5159) that this constitutes a bug in `QueryPerformanceCounter` / hyper-v as it should guarantee monotonicity. **We have reported this bug to the hyper-v owners and we're pushing for a fix**.

Still, I think it _would be nice_ if libuv could be robust to this kind of platform failure. I'd understand if the libuv maintainers choose not to adopt a workaround for this bug, like they have in the past. But I figured it can't hurt to propose an alternative design.

**Comment by vtjnash** [comment]
Can you run some of the test scripts from earlier here to print out info when it fails, to show if this is a similar or entirely different issue

https://github.com/libuv/libuv/issues/1633#issuecomment-633513828
