### ISSUE TITLE
handle EHOSTDOWN

### ISSUE THREAD

**Issue by Ognian** [libuv/libuv#195]
This is a mirror of https://github.com/joyent/libuv/issues/1512 .
I'm not sure if you have handled this...

**Comment by rowild** [comment]
This makes npm fail, when trying to install modules via npm.
Any solutions?

**Comment by bnoordhuis** [comment]
Fixed by 3f910a0.

**Comment by yunong** [comment]
Has this been fixed? I'm running node v0.12 on Yosemite and am still seeing: 
```
Assertion failed: (0), function uv_err_name, file ../deps/uv/src/uv-common.c, line 75.
```

**Comment by saghul** [comment]
@yunong yes, but the builtin libuv in Node hasn't been updated.

**Comment by vveerrgg** [comment]
@saghul is there a workaround to Node to pass the fail?   I've been trying to figure out a way around this error.

**Comment by bnoordhuis** [comment]
@vveerrgg You'd have to hand-upgrade the libuv that's bundled with joyent/node.

**Comment by saghul** [comment]
@vveerrgg looks like Node 0.12.1 will contain the fix, but before that
there is nothing you can do other than manually patching as Ben suggested.

**Comment by vveerrgg** [comment]
Thanks @saghul I'll give that a try.

**Comment by vveerrgg** [comment]
for anyone else who might be in the same problem... looks like this set of commands will also update node (which may have been updated)

> sudo brew uninstall node
> brew update
> brew upgrade
> brew cleanup
> brew install node
> sudo chown -R *YourUsernameHere* /usr/local
> brew link --overwrite node
> sudo brew postinstall node

I kinda don't know *exactly* what I'm doing... but it seemed to fix the error for me.

**Comment by ibash** [comment]
For posterity - it looks like Node 12.1 does *not* include the fix.

**Comment by saghul** [comment]
I know, it's 12.2. which will.

**Comment by sjackman** [comment]
I saw this error just now with node 0.12.2.
```
❯❯❯ npm install -g npm@latest
Assertion failed: (0), function uv_err_name, file ../deps/uv/src/uv-common.c, line 75.
❯❯❯ node --version
v0.12.2
❯❯❯ npm --version
2.7.5
```

**Comment by saghul** [comment]
Can you inspect the core dump and check the error code?

**Comment by dwaligora** [comment]
I got the same error still...

**Comment by saghul** [comment]
What is the unmapped errno?

**Comment by dwaligora** [comment]
node `0.12.12`:

> node: ../deps/uv/src/uv-common.c:75: uv_err_name: Assertion `0' failed.
Aborted

**Comment by saghul** [comment]
Can you please paste the entire backtrace? Also, the unmapped code would be
the value of "err" when passed to that function.

Last, do you have a reliable way to reproduce it?

**Comment by mauvm** [comment]
@vveerrgg Thanks, that also worked for me! I'd suggest others to use this slightly less intrusive version first though:

```bash
brew uninstall node
brew update
brew upgrade --all
brew cleanup
brew install node
```
