### ISSUE TITLE
unix: uv_async_send takes long latency on single core CPU again

### ISSUE THREAD

**Issue by Parallel-Hao** [libuv/libuv#2949]
* **Version**:  v1.x
* **Platform**:  Linux 4.15.0-88-generic

The relevant issue: https://github.com/libuv/libuv/issues/2769
The commit to solve the issue: https://github.com/libuv/libuv/commit/a9d9d4ea1b628368170fea18b042483f850e48a1

The test case is almost same as the above issue, including two threads, one (A) for libuv event loop and the other one (B) for sending event requests. Also, the process is pinned to one core. The difference with the above issue is that this time thread B does some computation (e.g., matrix multiplication) before sending event requests. The experiment shows the more computation thread B does, the longer latency the `uv_async_send()` takes. Further, I found the `sched_yield()` introduced from the above commit cannot truly yield CPU, which means thread A spins until running out its time slice in the case that thread B has heavy computations.

My guess is Linux CFS scheduler try not to schedule thread B for fairness in such case, since the computation of thread B consumed too much time slice compared to A. However, the fairness breaks the semantics here that thread A should yield CPU with 100% chance. According to `sched_yield()` manual, this function just moves the calling thread to the end of the scheduling queue and does not guarantee to schedule other threads. It seems no system call in Linux is provided to truly yield CPU.

After some search and try, it seems that `sleep(0)` is able to provide such truly (very high chance at least) yield function. Although this solution fixes my problem successfully, I am not sure this is the final solution for libuv. Because `sleep()` implemented by glibc is based on `nanosleep()` system call, which works for Linux, it is a concern whether `sleep(0)` can apply to other *nix systems.

**Comment by bnoordhuis** [comment]
I think the problem with `nanosleep()` is timer slack.

The linux kernel applies a performance optimization where it rounds up timeouts (the slack) in order to coalesce them. A zero timeout `nanosleep()` system call can sleep for 50 us or more because of slack. I expect that to negatively affect performance in an unpredictable manner.

It's possible to temporarily change the slack but that means two extra system calls in `uv__async_spin()` and that function should be _fast_.

I don't have time at the moment to do an in-depth investigation, but if you do, you know what to pay attention to now. :-)

**Comment by bnoordhuis** [comment]
Completely untested (not even if it compiles) but this is the basic idea:
```diff
diff --git a/src/unix/async.c b/src/unix/async.c
index 5f58fb88..56274d33 100644
--- a/src/unix/async.c
+++ b/src/unix/async.c
@@ -36,6 +36,8 @@
 
 #ifdef __linux__
 #include <sys/eventfd.h>
+#include <sys/prctl.h>
+#include <time.h>
 #endif
 
 static void uv__async_send(uv_loop_t* loop);
@@ -82,9 +84,13 @@ int uv_async_send(uv_async_t* handle) {
 
 /* Only call this from the event loop thread. */
 static int uv__async_spin(uv_async_t* handle) {
+  unsigned long slack;
   int i;
   int rc;
 
+  slack = (unsigned long) -1;
+  (void) &slack;
+
   for (;;) {
     /* 997 is not completely chosen at random. It's a prime number, acyclical
      * by nature, and should therefore hopefully dampen sympathetic resonance.
@@ -97,18 +103,44 @@ static int uv__async_spin(uv_async_t* handle) {
       rc = cmpxchgi(&handle->pending, 2, 0);
 
       if (rc != 1)
-        return rc;
+        goto done;
 
       /* Other thread is busy with this handle, spin until it's done. */
       cpu_relax();
     }
 
+#ifdef __linux__
+  if (slack == (unsigned long) -1) {
+    if (prctl(PR_GET_TIMERSLACK, &slack))
+      abort();
+    if (prctl(PR_SET_TIMERSLACK, 0))
+      abort();
+  }
+
+  {
+    struct timespec ts;
+    ts.tv_sec = 0;
+    ts.tv_nsec = 0;
+    nanosleep(&ts, NULL);
+  }
+#else
     /* Yield the CPU. We may have preempted the other thread while it's
      * inside the critical section and if it's running on the same CPU
      * as us, we'll just burn CPU cycles until the end of our time slice.
      */
     sched_yield();
+#endif
   }
+
+done:
+
+#ifdef __linux__
+  if (slack != (unsigned long) -1)
+    if (prctl(PR_SET_TIMERSLACK, slack))
+      abort();
+#endif
+
+  return rc;
 }
 
 
```

**Comment by Parallel-Hao** [comment]
@bnoordhuis  I made a PR based on your suggestion. One thing I need to explain is the timer slack value, which is set with 3000 nanoseconds. This is an empirical value. Otherwise it cannot really yield with less than 3000 ns on my platform.

**Comment by DariusBabrauskas** [comment]
Hello,
Why hasn't this serious bug been fixed yet?
I had a lot of problems before I found this bug. Then I found these user reports.
The shed_yield function is clearly written not to be used in "user space", due to all sorts of problems. This is what happened on my 1-core, arm 600Mhz system. When I start it with strace, node loops on the shed_yield log message. When I turn off strace, node recovers. I replaced shed_yield with usleep(0) - it no longer loops. strace slows down the work - which emulates the system load. Due to this loop, CPU consumption increases by 99%.
Note: now there is another mystical cycle 997 before shed_yield() - which heats the CPU. I didn't look into it much, but maybe if I made it with futex it would work much more reliably, faster and wouldn't waste CPU.

**Comment by vtjnash** [comment]
This was fixed a long time ago in fact, but not closed

**Comment by DariusBabrauskas** [comment]
> This was fixed a long time ago in fact, but not closed
Sorry, but I still see shed_yield still used.
https://github.com/libuv/libuv/blob/f87c8e4f70f234b952d9c47b15fb567f78e5f399/src/uv-common.c#L989

**Comment by vtjnash** [comment]
It is used only for uv_close now, which applications shouldn't use on these handles — and particularly they shouldn't use it while actively using the handle
